##
## EPITECH PROJECT, 2022
## Makefiles
## File description:
## make files
##

all:
	@ $(MAKE) -sC ./my/
	@ $(MAKE) -sC ./my_printf/

clean:
	@ $(MAKE) clean -sC ./my/
	@ $(MAKE) clean -sC ./my_printf/

fclean:
	@ $(MAKE) fclean -sC ./my/
	@ $(MAKE) fclean -sC ./my_printf/

re: fclean all

.PHONY:	clean fclean re debug
